== SDK Release Documentation

The release process results in new versions of the packages being published on npm. The version numbers on all packages must always be the same.

=== How Releases Work

The release process takes place in CircleCI. CircleCI notices a new release being created and kicks off a special release workflow. The following steps take place:

* A standard build job runs, i.e. the code is built and tested.
* If the build is successful then a release job runs.
  ** The each individual SDK is built and tested
  ** Each individual SDK is published on npm.

A small amount of preparation needs to take place before this process kicks off. Version numbers need to be updated accordingly using the scripts provided.

=== How to Prepare a Release

Ensure the git repo is clean and there are no outstanding changes. Then check out a new branch.

[source, bash]
--
git checkout -b release-x.y.z
--

**From the root directory** run the `prep-release` script.

[source, bash]
--
npm run release:prep
--

This script will interactively prompt you and ask what version you would like to update to. Select the appropriate version according to link:https://semver.org[Semver.]

[source,bash]
--
? Select a new version (currently 0.1.4) (Use arrow keys)
â¯ Patch (0.1.5)
  Minor (0.2.0)
  Major (1.0.0)
  Prepatch (0.1.5-alpha.0)
  Preminor (0.2.0-alpha.0)
  Premajor (1.0.0-alpha.0)
  Custom Prerelease
  Custom Version


Changes:
 - apollo-voyager-example: 0.1.4 => 0.1.5 (private)
 - @aerogear/apollo-voyager-audit: 0.1.4 => 0.1.5
 - @aerogear/apollo-voyager-keycloak: 0.1.4 => 0.1.5
 - @aerogear/apollo-voyager-metrics: 0.1.4 => 0.1.5
 - @aerogear/apollo-voyager-server: 0.1.4 => 0.1.5
 - @aerogear/apollo-voyager-tools: 0.1.4 => 0.1.5

? Are you sure you want to publish these packages? (ynH) y
Repository is ready for release.
--

Use `git status` to verify that the version numbers in the correct files have been updated.

[source, bash]
--
On branch release-0.1.5
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        renamed:    doc/guides/publishing.md -> doc/guides/publishing.adoc

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   examples/package.json
        modified:   lerna.json
        modified:   packages/apollo-voyager-audit/package.json
        modified:   packages/apollo-voyager-keycloak/package.json
        modified:   packages/apollo-voyager-metrics/package.json
        modified:   packages/apollo-voyager-server/package.json
        modified:   packages/apollo-voyager-tools/package.json
--

Commit and push these changes, then open a Pull Request to `master`.

[source, bash]
--
git commit -am 'release version x.y.z'
--

Once your changes have been merged to master, you can continue and release to npm.

=== How to Release

To kick off a release to npm, simply link:https://help.github.com/articles/creating-releases/[Create a Release] in Github. **You must use the exact `x.y.z` format** for the release tag or the release will fail.

This will kick off the automatic release process in CircleCI.
