= Deploying your Data Sync server application

.Prerequisites
* You have a working Data Sync server application (Node.js)
* Your application source code is in a publicly accessible Git repository.

NOTE: If the Data Sync server application is in a private repo,
then follow the link:https://docs.openshift.com/container-platform/3.11/dev_guide/application_lifecycle/new_app.html[Creating New Applications]
documentation which includes steps for using private git repositories.

. Log in to the openshift web console.
. Click the _Create Project_ button and fill out the form to create a new project for your application.
. Navigate to the project overview screen
. Use the search bar in the top right corner to search for 'Data Sync App'.
. In the Configuration section:
.. Enter the Git URL for the application repository.
.. Fill out the required fields (indicated by a *).
.. Fill out any optional fields if necessary.
. Complete the wizard start provisioning the Data Sync server application.
. Wait for the service to become ready.
. In project overview use the application URL displayed in the top right corner to verify your application is available.
