[id="server-using-mutations-with-a-data-sync-server-and-a-data-sync-client-{context}"]
= Using Mutations with a Data Sync Server

Build a Data Sync Server and query the mutation.
The Data Sync Server will be running locally in this procedure.

.Prerequisites

* link:https://github.com/jstaffor/mobile-docs/blob/master/modules/ROOT/pages/_partials/sync/server-getting-started.adoc[Getting Started with Hello World Data Sync].
* You are familiar with Data Sync Server operations, for example, stopping and starting Data Sync Server.

.Procedure

. If the Data Sync Server is running, stop it.
+
. Edit the `index.js` file and replace its contents with the following content:
+
[source,javascript]
----
const express = require('express')
//Include our server libraries
const { VoyagerServer, gql } = require('@aerogear/voyager-server')

//Provide your graphql schema
const typeDefs = gql`
type Query {
  info: String!
  addressBook: [Person!]!
}

type Mutation {
  post(name: String!, address: String!): Person!
}

type Person {
  id: ID!
  address: String!
  name: String!
}
`

let persons = [{
  id: 'person-0',
  name: 'Alice Roberts',
  address: '1 Red Square, Waterford'
}]

let idCount = persons.length
const resolvers = {
  Query: {
    info: () => `This is a simple example`,
    addressBook: () => persons,
  },
  Mutation: {

    post: (parent, args) => {
       const person = {
        id: `person-${idCount++}`,
        address: args.address,
        name: args.name,
      }
      persons.push(person)
      return person
    }
  },
}

//Initialize the library with your GraphQL information
const server = VoyagerServer({
  typeDefs,
  resolvers
})

//Connect the server to express
const app = express()
server.applyMiddleware({ app })

app.listen(4000, () =>
  console.log(`🚀 Server ready at http://localhost:4000/graphql`)
)
----
+

.Verification steps

. Start the server.
+
. Open an internet browser and browse to `http://localhost:4000/graphql`.
+
. To list the contents of the address book, execute the following command in the GraphQL window:
+
[source,javascript]
----
{
  addressBook {
    name
    address

  }
}
----
+
For the example above, the output should be:

[source,javascript]
----
{
  "data": {
    "addressBook": [
      {
        "name": "Alice Roberts",
        "address": "1 Red Square, Waterford"
      }
    ]
  }
}
----

.Additional resources

* For more information about Mutations, Queries and Input Types, please see link:https://graphql.org/graphql-js/mutations-and-input-types/[Mutations and Input Types].
* For more information about Resolver Maps, see link:https://www.apollographql.com/docs/graphql-tools/resolvers#resolver-map[Resolver Maps].
