[[sync-js-client-improving-ui-performance]]

= Improving UI performance

By default mutations are not applied to the UI until responses are received from the server. To provide a better user experience, an application may want to update the UI immediately. link:https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-mutation-options-optimisticResponse[Optimistic response] is an easy way to achieve this goal, and {sync-client} provides a helper method to work with optimistic responses.  The `optimisticResponse` feature and the <<#sync-client-offline-queue-listener, offlineQueueListener>> can be used together to deliver a great offline experience for an application.

.Procedure

. To enable optomistic response, run the following command:
+
[source, javascript]
----
 import { createOptimisticResponse } from "@aerogear/voyager-client";

 client.mutate({
   mutation: ADD_TASK,
   variables: item,
   optimisticResponse: createOptimisticResponse("createTask", "Task", item);
 });
----

+
. Use the `optimisticResponse` flag to detect if the provided data is an optimistic response.

//Is this id mapping completely transparent to developers? If not, what action do they need to take? If it is, then we should probably remove this section.
// === Mapping Client and Server ID for Optimistic Responses

// When using `OptimisticReponse` helper from SDK specific mutations that create new element response is going to have client side generated id. Subsequent edits for this objects will also refer to this id. When becoming online, all offline changes are going to be performed in specific order updating client side id with id returned from server for subsequent edits.


//tag::excludeDownstream[]
.Additional resources
See the xref:showcase-apps.adoc[Showcase Apps section] for more information.
//end::excludeDownstream[]

