
= Provisioning the {sync-service} server applications using templates

{sync-service} offers following OpenShift templates
that will help developers with provisioning their DataSync applications to OpenShift platform.

Templates:

- DataSync App

The DataSync App template allows developers to deploy the Node.js DataSync App on Openshift using source code only.
_Node s2i_  is used to build the Data Sync App image.
NOTE: You must set the `NODE_ENV` environment variable to `development` and redeploy the pod to ensure access to the GraphQL playground.

The DataSync App can connect with other services running on OpenShift and can also connect to external data sources.

- DataSync Showcase

Showcase application will deploy fully functional server with example Task implementation.
Server side requires client application available on github link:https://github.com/aerogear/ionic-showcase[aerogear/ionic-showcase]

Note: Use the Showcase server template for demo purposes only. Do not use this template in a production environment.


// tag::excludeUpstream[]
When running on Red Hat Managed Integration templates will be available in *Mobile* > *App*  category in OpenShift catalog
// end::excludeUpstream[]


// tag::excludeDownstream[]
Templates along with documentation can be found in link:https://github.com/aerogear/datasync-deployment[datasync-deployment] repository.
// end::excludeDownstream[]
